$content = Get-Content "index.html" -Raw -Encoding UTF8
$content = $content.Replace("Ã§", "ç")
$content = $content.Replace("Ã£", "ã")
$content = $content.Replace("Ã¡", "á")
$content = $content.Replace("Ã©", "é")
$content = $content.Replace("Ã­", "í")
$content = $content.Replace("Ã³", "ó")
$content = $content.Replace("Ãº", "ú")
$content = $content.Replace("Ã¢", "â")
$content = $content.Replace("Ãª", "ê")
$content = $content.Replace("Ã´", "ô")
$content = $content.Replace("Ãµ", "õ")
$content = $content.Replace("Ã‡", "Ç")
$content = $content.Replace("Ãƒ", "Ã")
$content = $content.Replace("Ã‰", "É")
$content = $content.Replace("Ã“", "Ó")
$content = $content.Replace("Ã•", "Õ")
$content = $content.Replace("Ã‚", "Â")
$content = $content.Replace("ÃŠ", "Ê")
$content = $content.Replace("Ãš", "Ú")
$content = $content.Replace("Ã€", "À")
$content = $content.Replace("Ã ", "À")
$content = $content.Replace("Ã ", "Á")
$content = $content.Replace("Âº", "º")
$content = $content.Replace("Âª", "ª")
$content = $content.Replace("â€”", "—")
$content = $content.Replace("â€œ", "“")
$content = $content.Replace("â€ ", "”")
$content = $content.Replace("â€™", "’")

# Since Set-Content adds BOM in PS5, we use a different way to write UTF8 without BOM
$bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
[System.IO.File]::WriteAllBytes("c:\Users\lucas\Documents\Projetos\OFERTA ODAT 1.0\index.html", $bytes)
Write-Host "Done."
